### ISSUE TITLE
EXTENSION: Need to format portrait orientation photos differently

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/NewsPix#13]
Newspix makes them fill the whole width of the screen but that cuts off portraint orientation -- see this example which Matt put in on the admin side:
http://www.sentinelsource.com/news/local/maclean-to-end--year-run-as-keene-city-manager/article_4484f6b8-00ed-5dc5-8075-0c453f92761c.html?mode=image&photo=0

**Comment by jayvachon** [comment]
how did we want to style this? pillarboxing?
