### ISSUE TITLE
ADMIN: Add analytics/metrics section

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/NewsPix#14]
Just thought about this - before we launch we should have a place in the admin area where Keene can review engagement. E.g. how many times did people click vs. opportunities to click. And do we want to try to capture IP address to determine geography of users in some way? Or stay away from user-centered metrics altogether? Jay - let's talk about this to flesh out something simple for a first version.

**Comment by jayvachon** [comment]
basic analytics are up - closing this for now but we can reopen if there are any other ideas for data to capture
