### ISSUE TITLE
ADMIN: Analytics numbers not showing up

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/NewsPix#15]
I'm not seeing the analytics numbers show up on the deployed version -- 

http://dev.newspix.today/analytics

**Comment by kanarinka** [comment]
OK I just did a little db hunting and there is no "load_count" data or "click_count" data in the production DB. Perhaps there's an issue with getting some of those initial values set to 0 to start with so that they can increment? 

here's the content that is there:

{ "_id" : ObjectId("550d5c204dee48aac62fa02b"), "headline" : "Mayor sends Keene Pumpkin Festival decision back for another round", "url" : "http://www.sentinelsource.com/news/local/mayor-sends-keene-pumpkin-festival-decision-back-for-another-round/article_28cc4a85-fd5a-5c4a-9bb0-e514cf40bd83.html?mode=story", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/2/7d/27d76939-72fb-5d3c-850e-994274a0831d/550c1ceb411f0.image.jpg", "date" : ISODate("2015-03-21T00:00:00Z") }
{ "_id" : ObjectId("55104c904dee48431bc7b537"), "headline" : "Local women try to raise awareness about painful disease", "url" : "http://www.sentinelsource.com/news/local/local-women-try-to-raise-awareness-about-painful-disease/article_e8f12db0-74e0-5cd9-986d-a0a803f17d7d.html", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/3/fd/3fde12db-5ebf-59a2-861b-30abedfbb6f3/550ffaf15e1ef.image.jpg", "date" : ISODate("2015-03-23T00:00:00Z") }
{ "_id" : ObjectId("55107c664dee48431bc7b538"), "headline" : "Massachusetts man plans to revitalize Winchester's Main Street", "url" : "http://www.sentinelsource.com/news/local/new-distillery-on-tap-in-winchester/article_a7eddc10-0cfb-5049-91f9-84c7e5f7757f.html", "image" : "http://www.sentinelsource.com/news/local/new-distillery-on-tap-in-winchester/article_a7eddc10-0cfb-5049-91f9-84c7e5f7757f.html?mode=image&photo=1", "date" : ISODate("2015-03-24T00:00:00Z") }
{ "_id" : ObjectId("55107d2f4dee48431bc7b539"), "headline" : "New distillery on tap in Winchester", "url" : "http://www.sentinelsource.com/news/local/new-distillery-on-tap-in-winchester/article_a7eddc10-0cfb-5049-91f9-84c7e5f7757f.html", "image" : "http://www.sentinelsource.com/news/local/new-distillery-on-tap-in-winchester/article_a7eddc10-0cfb-5049-91f9-84c7e5f7757f.html?mode=image&photo=1", "date" : ISODate("2015-03-23T00:00:00Z") }
{ "_id" : ObjectId("553e5bd64dee484f94d6d54e"), "headline" : "Atomization--breaking stories into component pieces", "url" : "https://medium.com/@matthewscarroll/the-atomization-of-stories-eaf06f32da31", "image" : "https://d262ilb51hltx0.cloudfront.net/max/1280/1*eWSE6HYNsiFbWqUAyjY6XQ.png", "date" : ISODate("2015-04-28T00:00:00Z") }
{ "_id" : ObjectId("553e5c914dee484f94d6d54f"), "headline" : "Atomization--breaking stories into component pieces", "url" : "https://medium.com/@matthewscarroll/the-atomization-of-stories-eaf06f32da31", "image" : "https://d262ilb51hltx0.cloudfront.net/max/1280/1*eWSE6HYNsiFbWqUAyjY6XQ.png", "date" : ISODate("2015-04-27T00:00:00Z") }
{ "_id" : ObjectId("553e5d4d4dee484f94d6d550"), "headline" : "Mapping vernal pools, one at a time", "url" : "http://www.sentinelsource.com/news/local/mapping-vernal-pools-one-at-a-time/article_befc7e12-3ce8-510e-a26b-bb3bc06e8a80.html", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/9/05/90581acb-ea65-5211-9a03-dce77a74334e/553c2440a2a17.preview-300.jpg", "date" : ISODate("2015-04-27T00:00:00Z") }
{ "_id" : ObjectId("553e5dd14dee484f94d6d551"), "headline" : "Elm St fire in Keene", "url" : "http://www.sentinelsource.com/news/local/images-from-the-elm-st-fire-in-keene/collection_3b4f6900-bbe9-5bcf-b225-c4034db99e16.html", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/0/1f/01fb591f-c24f-53da-b00c-c177c507ec91/5531894142003.image.jpg", "date" : ISODate("2015-04-27T00:00:00Z") }
{ "_id" : ObjectId("553e5df44dee484f94d6d552"), "headline" : "Fighting Elm St fire", "url" : "http://www.sentinelsource.com/news/local/images-from-the-elm-st-fire-in-keene/collection_3b4f6900-bbe9-5bcf-b225-c4034db99e16.html", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/c/df/cdfabdb5-5ca4-5d08-8950-87102393fc09/55318db02cdbf.image.jpg", "date" : ISODate("2015-04-27T00:00:00Z") }
{ "_id" : ObjectId("553e5e5b4dee484f94d6d553"), "headline" : "Fighting a stubborn fire", "url" : "http://www.sentinelsource.com/news/local/images-from-the-elm-st-fire-in-keene/collection_3b4f6900-bbe9-5bcf-b225-c4034db99e16.html", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/d/0a/d0a881ef-3318-515e-adf8-d6cc351caa6b/5531866441689.image.jpg", "date" : ISODate("2015-04-27T00:00:00Z") }
{ "_id" : ObjectId("553e5ead4dee484f94d6d554"), "headline" : "Monadnock High makes history in DisneyWorld", "url" : "http://www.sentinelsource.com/features/education/monadnock-high-marching-band-makes-music-at-disney-world/article_e7261724-fd38-571b-9262-de133f9b8901.html#.VT4gzF4JVh8.twitter", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/c/2f/c2f25752-b0b8-51a0-bbe3-6f1aee572ed9/55395aa7d1680.image.jpg?resize=300%2C237", "date" : ISODate("2015-04-27T00:00:00Z") }
{ "_id" : ObjectId("554110124dee4899b9f32741"), "headline" : "Massachusetts man sentenced in Franklin Pierce University sexual assault", "url" : "http://www.sentinelsource.com/news/local/massachusetts-man-sentenced-in-franklin-pierce-university-sexual-assault/article_039f98b9-4fe5-5c4b-a66a-2618d061a4f8.html", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/c/f0/cf09c28f-1cb2-561e-a8e8-b5241bd0facc/5540c4462dffe.preview-300.jpg", "date" : ISODate("2015-04-29T00:00:00Z") }
{ "_id" : ObjectId("5541124d4dee4899b9f32742"), "headline" : "test", "url" : "http://www.sentinelsource.com/news/local/massachusetts-man-sentenced-in-franklin-pierce-university-sexual-assault/article_039f98b9-4fe5-5c4b-a66a-2618d061a4f8.html", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/c/f0/cf09c28f-1cb2-561e-a8e8-b5241bd0facc/5540c4462dffe.preview-300.jpg", "date" : ISODate("2015-04-30T00:00:00Z") }
{ "_id" : ObjectId("554211be4dee4899b9f32743"), "headline" : "Mass. man sentenced", "url" : "http://www.sentinelsource.com/news/local/massachusetts-man-sentenced-in-franklin-pierce-university-sexual-assault/article_039f98b9-4fe5-5c4b-a66a-2618d061a4f8.html", "image" : "http://www.sentinelsource.com/news/local/massachusetts-man-sentenced-in-franklin-pierce-university-sexual-assault/article_039f98b9-4fe5-5c4b-a66a-2618d061a4f8.html?mode=image&photo=0", "date" : ISODate("2015-04-30T00:00:00Z") }
{ "_id" : ObjectId("554212064dee4899b9f32744"), "headline" : "Residents upset by pipeline plan", "url" : "http://www.sentinelsource.com/news/local/shame-on-you-richmond-residents-grill-kinder-morgan-over-pipeline/article_c8f37381-8749-50e5-86ef-17c44b763dee.html", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/4/f6/4f651e18-d83f-53bb-804a-02be7b11acd2/553fb02c72bb9.preview-300.jpg", "date" : ISODate("2015-04-30T00:00:00Z") }
{ "_id" : ObjectId("554b71d14dee48264025f27b"), "headline" : "Hedder 1", "url" : "http://www.sentinelsource.com/news/local/images-from-the-elm-st-fire-in-keene/collection_3b4f6900-bbe9-5bcf-b225-c4034db99e16.html", "image" : "http://www.sentinelsource.com/news/local/main-street-residents-still-not-ready-for-another-keene-historic/article_1c6d4769-1db2-5936-9377-fe3c7ba7ac3a.html", "date" : ISODate("2015-05-08T00:00:00Z") }
{ "_id" : ObjectId("554b71fc4dee48264025f27c"), "headline" : "hedder 2", "url" : "http://www.sentinelsource.com/news/local/images-from-the-elm-st-fire-in-keene/collection_3b4f6900-bbe9-5bcf-b225-c4034db99e16.html", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/7/a7/7a7815b2-7145-5492-91ae-bfb902777330/554a0b6eb1254.image.jpg?resize=300%2C208", "date" : ISODate("2015-05-08T00:00:00Z") }
{ "_id" : ObjectId("554b72214dee48264025f27d"), "headline" : "hedder 3", "url" : "http://www.sentinelsource.com/news/local/images-from-the-elm-st-fire-in-keene/collection_3b4f6900-bbe9-5bcf-b225-c4034db99e16.html", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/d/14/d1496b67-d763-5542-99d5-31b706bc2268/554a76c10a02e.image.jpg", "date" : ISODate("2015-05-07T00:00:00Z") }
{ "_id" : ObjectId("554b72784dee48264025f27e"), "headline" : "hedder 4", "url" : "http://www.sentinelsource.com/news/local/images-from-the-elm-st-fire-in-keene/collection_3b4f6900-bbe9-5bcf-b225-c4034db99e16.html", "image" : "http://bloximages.chicago2.vip.townnews.com/sentinelsource.com/content/tncms/assets/v3/editorial/7/84/784fb942-075f-5e36-b5ef-cd7de9459343/554a2175847f7.image.jpg", "date" : ISODate("2015-05-07T00:00:00Z") }
{ "_id" : ObjectId("554b72a14dee48264025f27f"), "headline" : "Video URL", "url" : "http://www.sentinelsource.com/news/local/images-from-the-elm-st-fire-in-keene/collection_3b4f6900-bbe9-5bcf-b225-c4034db99e16.html", "image" : "http://launch.newsinc.com/?type=VideoPlayer/16x9&videoId=29030846&trackingGroup=91092&widgetId=11465&playlistId=994&siteSection=keene_nws_non_sec&embedOriginUrl=http%253A%252F%252Fwww.sentinelsource.com%252Fnews%252Flocal%252Fnh-event-leaders-featured-in-panel-as-part-of-tourism%252Farticle_b7ada5da-05f0-5eba-9d1d-f1a74d37886e.html%253Fmode%253Dimage%2526photo%253D0", "date" : ISODate("2015-05-07T00:00:00Z") }

**Comment by jayvachon** [comment]
if you add new stories those fields will be initialized now, but because these stories were added to the db before I started tracking loads & clicks the fields are absent. still, the server should check for & handle missing fields

**Comment by kanarinka** [comment]
Looks like it's doing load numbers but not click numbers -- try it out here http://dev.newspix.today/analytics

**Comment by jayvachon** [comment]
believe I've fixed this but it should be tested on the server
